modLoader = "javafml"
loaderVersion = "[34,)"
license = "MIT"
issueTrackerURL = "https://github.com/ochotonida/some-assembly-required/issues"

[[mods]]
modId = "someassemblyrequired"
version = "1.16.4-1.0.0"
displayName = "Some Assembly Required"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/some-assembly-required"
logoFile = "logo.png"
authors = "ochotonida"
credits = "Based on the fabric mod Sandwichable by FoundationGames"
description = '''
Design your own sandwiches!
'''

[[dependencies.someassemblyrequired]]
modId = "forge"
mandatory = true
versionRange = "[34,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.someassemblyrequired]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3,1.17)"
ordering = "NONE"
side = "BOTH"
