modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT"
issueTrackerURL = "https://github.com/ochotonida/some-assembly-required/issues"

[[mods]]
modId = "some-assembly-required"
version = "1.18.1-2.0.0"
displayName = "Some Assembly Required"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/some-assembly-required"
logoFile = "logo.png"
authors = "ochotonida"
credits = "Based on the fabric mod Sandwichable by FoundationGames"
description = '''
Design your own sandwiches!
'''

[[dependencies.some-assembly-required]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.some-assembly-required]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"
